language: python
python:
  - 2.7

# Setup anaconda
before_install:
  - wget http://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh
  - chmod +x miniconda.sh
  - ./miniconda.sh -b
  - export PATH=/home/travis/miniconda/bin:$PATH
  - conda update --yes conda

install:
  - conda install --yes python=$TRAVIS_PYTHON_VERSION setuptools numpy scipy gdal pillow basemap nose netcdf4
  - conda install --yes -c jjhelmus gdal-data
  - conda install --yes -c rsignell proj4
  - python setup.py install
  - export GDAL_DATA=/home/travis/miniconda/share/gdal

script: "cd ..; nosetests nansat.tests"
